### PR TITLE
Allow list option

### PR DESCRIPTION
**Pull request by meejah**
This adds a `--disallow-list` command-line option, with an "allow_list" in the code and a couple minor refactorings. See also #53

### CODE REVIEW

**Comment by meejah** [comment]
Hmm, does the windows build just not work? Or did I somehow affect that util test with this patch??!!

**Comment by warner** [comment]
I must have broken the windows build a few weeks ago, when I was trying to improve test coverage and did a `mock.patch()` on something that didn't exist on windows. If you rebase, it should be fixed now.

Could we put this functionality on `rendezvous.AppNamespace` instead of on the websocket-specific frontend server? I've got two motivations:

* future frontends (non-websocket) should honor this setting too
* some apps will want to allow this, some won't. (in fact really it's likely to be that some nameplates will want themselves to be tab-completable, and some won't, like offline/human-generated wormhole codes). So I'd like to move this closer to the nameplate record, and putting it in `AppNamespace` is as close as we can get without actually changing the DB schema yet.

Basically we want `AppNamespace.get_nameplate_ids` to return an empty list if nameplate-listing has been disabled. We need to rename the existing function to `_get_nameplate_ids` so it can continue to be used by `_find_available_nameplate_id` (which needs it to do allocation). Then the new `get_nameplate_ids()` will just be a wrapper that checks the permission flag and then either returns `self._get_nameplate_ids()` or `[]`. The permission flag should be passed down into the `AppNamespace` through `Rendezvous.get_app()`, so the `WebSocketRendezvousFactory` shouldn't see it at all.

If/when we make individual nameplates listable or not, I think we'll use an AND check. `_get_nameplate_ids()` will return an empty list if the app permission is turned off, else it will return just the nameplates that the DB record says are listable.

We've talked about allowing *allocation* to be enabled on a per-frontend basis, which would make some of these feature/permission switches want to live on a Factory, but I think I like our idea about API tokens better (so a co-located specially-blessed "client" uses its secret token to perform allocation, rather than using a special network socket that's unreachable from anywhere else).

Also, could you squash this down into one commit? Thanks!

**Comment by meejah** [comment]
Okay, I updated as per the comment.

I also added some unit-tests.

**Comment by warner** [comment]
looks good.. landing now

**Comment by warner** [comment]
note to self: when reviewing, I missed the fact that the new `--disallow-list` option was only added to `wormhole-server start`, and not `wormhole-server restart`, causing today's server upgrade to have problems (quickly fixed by using stop+start instead of just "restart").

I should move the common arguments into a common class, and add test coverage for both `start` and `restart`.

**Pull request merged**
